### ISSUE TITLE
Supporting non-breaking spaces

### ISSUE THREAD

**Issue by AntMonss** [robertknight/tex-linebreak#5]
Hey ! 

First of all thanks a lot for the awesome lib; it gives super nice results for most use cases. 

I'm wondering if there would be a way to keep non-breaking spaces non-breakable tho. 
In some langages, take French for instance, we would put space before/after some given ponctuation marks, for instance 
Bonjour ?
or 
Bonjour !
or 
« Bonjour ».
I feel the lib just take them as regular spaces implying some ponctuation marks being break at the beginning of lines, making it hard to use without a dirty hack.

Is it something already supported and I'm missing something? Or could you maybe give some advises on how to tweak the lib to achieve it? I guess it would imply detecting nbsp and give them super high penalty somewhere in the algorythm.

Thanks a lot for your help !

![image](https://user-images.githubusercontent.com/47351769/127739629-f324e406-c392-4b8d-a8d1-5b7696841b83.png)

**Comment by robertknight** [comment]
Hello! - The conversion of an input string into a series of "boxes" (which represent words) separated by "glue" (which represents spaces) happens in `layoutItemsFromString`. See https://github.com/robertknight/tex-linebreak/blob/7d0c8d5a0d3baadfb14bb8ce6c1842d85398b21a/src/helpers.ts#L45

One way to create non-breaking spaces would be to change the regex that splits the input string into words (currently just `/\s+/`) so that it doesn't split on non-breaking spaces. The non-breaking spaces would then become part of the boxes. A downside of this is that this would prevent the layout algorithm from adjusting the size of a non-breaking space, since only "glue" items are stretchable. Making non-breaking spaces stretchable is probably a bit more involved, and might not be important. I think it would probably involve altering the logic related to the `canBreak` variable in the `breakLines` function to support "non-breakable glue (space) items".

**Comment by AntMonss** [comment]
Hey, thanks a lot for the hint, it works like a charm with the regex modification. 

I'll take a deeper look at the canBreak variable; maybe it could also the thing to tweak to handle orphans words, i.e. a single isolated word causing a full new line to be created at the end of a paragraph. Will keep you posted!
